---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kibana
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: "cookie"
spec:
 rules:
 - host: kibana.info
   http:
     paths:
     - path: /
       backend:
         serviceName: quickstart-kibana
         servicePort: 5601
